# Chi-Square Test

The Test is applied when you have two categorical variables from a single population . It is used to determine whether is a significant association between two varibles.

In [2]:
#It is the library used for chi-square test
import scipy.stats as stats 

In [5]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset = sns.load_dataset("tips")

In [6]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
#here we want to check from above dataset is that isthere any association between sex and smoker. we will find it using chi-square.
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [9]:
print(dataset_table.values)

[[60 97]
 [33 54]]


In [8]:
#Observed above values
Observed_Values = dataset_table.values
print("Observed Values :-\n", Observed_Values)

Observed Values :-
 [[60 97]
 [33 54]]


In [11]:
val = stats.chi2_contingency(dataset_table)

In [13]:
#It will our expected values
val

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [14]:
Expected_Values = val[3]

In [15]:
no_of_rows = len(dataset_table.iloc[0:2,0])
no_of_columns = len(dataset_table.iloc[0,0:2])
ddof = (no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-", ddof)
alpha = 0.05

Degree of Freedom:- 1


# Chi Square formula :
    
    
    
    
    X^2 = SUM OF (Observed- Expected)^2/Expected
    

In [17]:
from scipy.stats import chi2
chi_square = sum([(o-e)**2./e for o,e in zip(Observed_Values, Expected_Values)])
chi_square_statistic = chi_square[0] - chi_square[1]

In [18]:
print("chi-square statistic:- ", chi_square_statistic)

chi-square statistic:-  0.00045991588165738596


In [19]:
critical_value = chi2.ppf(q=1-alpha, df=ddof)
print("Critical_Value : ", critical_value)

Critical_Value :  3.841458820694124


In [21]:
#P-Value
p_value = 1-chi2.cdf(x=chi_square_statistic, df=ddof)
print("P-value: ", p_value)
print("Significance level: ", alpha)
print("Degree of Freedom: ", ddof)
print("P-value:", p_value)

P-value:  0.9828901589074648
Significance level:  0.05
Degree of Freedom:  1
P-value: 0.9828901589074648


In [22]:
if chi_square_statistic>=critical_value:
    print("Reject H0, There is a relationship between 2 categorical variables")
    
else:
    print("Retain H0, There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0, There is a relationship between 2 categorical variables")
    
else:
    print("Retain H0, There is no relationship between 2 categorical variables")
    

    


Retain H0, There is no relationship between 2 categorical variables
Retain H0, There is no relationship between 2 categorical variables
